featured_type:
  default: "topic"
  type: enum
  choices:
    - "topic"
    - "category"
  description: "Type of content to feature (topic or category)."

featured_id:
  default: 1
  type: integer
  description: "The ID of the featured topic or category."
